name: Atlas CI

on:
  [pull_request, push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Setup Maven
      # You may pin to the exact commit or the version.
      # uses: stCarolas/setup-maven@3c9ddfb1c6df927e174580018dd71e774bc7dd48
      uses: stCarolas/setup-maven@v4.1
      with:
        # Version Spec of the version to use.  Examples: 10.x, 10.15.1, >=10.15.0
        maven-version: 3.5.4 # optional, default is 3.5.4
    - name: Install Atlassian SDK
      # You may pin to the exact commit or the version.
      # uses: rodrigo-nogues/github-action-install-atlassian-sdk@4b695bc126676bb923332780bdc3c19d1fe6ce8b
      uses: rodrigo-nogues/github-action-install-atlassian-sdk@v1
    - name: Run Tests
      run: atlas-unit-test
